version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "stockcode-scraping"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-w5soiq4sxkqv"
s3_prefix = "stockcode-scraping"
region = "ap-northeast-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
